server:
  port: 8081
  servlet:
    context-path: /

spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#  resources:
#    static-locations: classpath:/resources/**
# * all ** anywhere

