server:
  port: 8081
  servlet:
    context-path: /
    jsp:
      init-parameters: true
spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  resources:
    static-location:{classpath:/resources/**,classpath:/resources/img/**}
# * all ** anywhere
